---
- name: copy master named.conf
  copy: 
    src: master-named.conf 
    dest: /etc/named.conf 
    owner: root 
    group: named 
    mode: 0640
  when: '"ns01" in inventory_hostname'

- name: copy slave named.conf
  copy: 
    src: slave-named.conf 
    dest: /etc/named.conf 
    owner: root 
    group: named 
    mode: 0640
  when: '"ns02" in inventory_hostname'

- name: copy zones
  copy: 
    src: "{{ item }}"
    dest: /etc/named/ 
    owner: root 
    group: named 
    mode: 0660
  with_fileglob:
    - named.*
  when: '"ns01" in inventory_hostname'

- name: copy resolv.conf to the servers
  copy: 
    src: servers-resolv.conf 
    dest: /etc/resolv.conf 
    owner: root 
    group: root 
    mode: 0644

- name: set /etc/named permissions
  file:
    path: /etc/named
    owner: root
    group: named
    mode: 0670

- name: set proper setype for /etc/named
  sefcontext:
    target: "/etc/named(/.*)?"
    setype: named_zone_t
    state: present

- name: apply file context to /etc/named
  command: restorecon -R -v /etc/named

- name: make sure selinux enabled
  selinux:
    policy: targeted
    state: enforcing

- name: ensure named is running and enabled
  service: 
    name: named 
    state: restarted 
    enabled: yes
